<?= $this->extend('admin_template/layout') ?>

<?= $this->section('content') ?>

<?php
$pageActions = '
    <button class="btn btn-primary btn-sm" onclick="exportCalendar()">
        <i class="fas fa-download"></i> Export Calendar
    </button>
';
?>

<?= $this->include('admin_template/partials/page_header', [
    'title' => 'Wedding Events Calendar',
    'subtitle' => 'View and manage all upcoming wedding ceremonies',
    'actions' => $pageActions
]) ?>

<!-- Calendar Navigation -->
<div class="card mb-3">
    <div class="card-body">
        <div class="calendar-nav">
            <div class="calendar-controls">
                <button class="btn btn-outline-secondary btn-sm" onclick="previousMonth()">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <h3 id="currentMonth" class="calendar-month-title"><?= date('F Y') ?></h3>
                <button class="btn btn-outline-secondary btn-sm" onclick="nextMonth()">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            <div class="view-controls">
                <button class="btn btn-sm btn-primary" onclick="setView('month')">Month</button>
                <button class="btn btn-sm btn-outline-primary" onclick="setView('week')">Week</button>
                <button class="btn btn-sm btn-outline-primary" onclick="setView('list')">List</button>
            </div>
        </div>
    </div>
</div>

<!-- Calendar Grid -->
<div class="card mb-3">
    <div class="card-body p-0">
        <div id="calendar-grid" class="calendar-grid">
            <!-- Calendar Header -->
            <div class="calendar-header">
                <div class="day-header">Sun</div>
                <div class="day-header">Mon</div>
                <div class="day-header">Tue</div>
                <div class="day-header">Wed</div>
                <div class="day-header">Thu</div>
                <div class="day-header">Fri</div>
                <div class="day-header">Sat</div>
            </div>
            
            <!-- Calendar Days will be generated by JavaScript -->
            <div id="calendar-days" class="calendar-days">
                <!-- Days will be populated dynamically -->
            </div>
        </div>

        <!-- List View (hidden by default) -->
        <div id="list-view" class="list-view" style="display: none;">
            <div class="events-list">
                <?php if (!empty($upcomingBookings)): ?>
                    <?php foreach ($upcomingBookings as $booking): ?>
                    <div class="event-list-item" data-date="<?= $booking['wedding_date'] ?>">
                        <div class="event-date-info">
                            <div class="event-day"><?= date('j', strtotime($booking['wedding_date'])) ?></div>
                            <div class="event-month"><?= date('M', strtotime($booking['wedding_date'])) ?></div>
                            <div class="event-year"><?= date('Y', strtotime($booking['wedding_date'])) ?></div>
                        </div>
                        <div class="event-details">
                            <h4>Wedding Ceremony</h4>
                            <p class="couple-names"><?= esc($booking['bride_name'] . ' & ' . $booking['groom_name']) ?></p>
                            <p class="event-location">
                                <i class="fas fa-map-marker-alt"></i>
                                <?= esc($booking['campus_name'] ?? 'Unknown Campus') ?>
                            </p>
                            <p class="event-time">
                                <i class="fas fa-clock"></i>
                                <?= date('g:i A', strtotime($booking['wedding_time'])) ?>
                            </p>
                        </div>
                        <div class="event-actions">
                            <span class="status-badge status-<?= $booking['status'] ?>"><?= ucfirst($booking['status']) ?></span>
                            <a href="<?= site_url('admin/booking/' . $booking['id']) ?>" class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-eye"></i>
                                View
                            </a>
                        </div>
                    </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="empty-calendar">
                        <i class="fas fa-calendar-times"></i>
                        <h4>No upcoming events</h4>
                        <p>There are no wedding ceremonies scheduled for the coming months.</p>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<!-- Legend -->
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Legend</h3>
    </div>
    <div class="card-body">
        <div class="legend-items">
            <div class="legend-item">
                <div class="legend-color status-pending"></div>
                <span>Pending</span>
            </div>
            <div class="legend-item">
                <div class="legend-color status-approved"></div>
                <span>Approved</span>
            </div>
            <div class="legend-item">
                <div class="legend-color status-completed"></div>
                <span>Completed</span>
            </div>
            <div class="legend-item">
                <div class="legend-color status-cancelled"></div>
                <span>Cancelled</span>
            </div>
        </div>
    </div>
</div>

<!-- Event Details Modal -->
<div class="modal-overlay" id="eventModal" style="display: none;">
    <div class="modal">
        <div class="modal-header">
            <h3 class="modal-title"><i class="fas fa-calendar-check"></i> Wedding Event Details</h3>
            <button type="button" class="modal-close" onclick="closeModal('eventModal')">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="modal-body" id="eventModalBody">
            <!-- Event details will be populated here -->
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" onclick="closeModal('eventModal')">Close</button>
            <a href="#" id="viewEventBtn" class="btn btn-primary">
                <i class="fas fa-eye"></i> View Booking
            </a>
        </div>
    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script>
// Calendar data from PHP
const eventsData = <?= json_encode($upcomingBookings ?? []) ?>;
let currentDate = new Date();
let currentView = 'month';

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
    renderCalendar();
});

function renderCalendar() {
    if (currentView === 'month') {
        renderMonthView();
    } else if (currentView === 'list') {
        showListView();
    }
    updateCurrentMonthDisplay();
}

function renderMonthView() {
    document.getElementById('calendar-grid').style.display = 'block';
    document.getElementById('list-view').style.display = 'none';
    
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    // Get first day of month and number of days
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const daysInMonth = lastDay.getDate();
    const startingDayOfWeek = firstDay.getDay();
    
    let html = '';
    
    // Add empty cells for days before month starts
    for (let i = 0; i < startingDayOfWeek; i++) {
        html += '<div class="calendar-day empty"></div>';
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const currentDateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayEvents = eventsData.filter(event => event.wedding_date === currentDateStr);
        const isToday = isDateToday(year, month, day);
        
        html += `<div class="calendar-day ${isToday ? 'today' : ''}" data-date="${currentDateStr}">
            <div class="day-number">${day}</div>
            <div class="day-events">`;
        
        dayEvents.forEach(event => {
            html += `<div class="event-item status-${event.status}" onclick="showEventDetails('${event.id}')">
                <div class="event-time">${formatTime(event.wedding_time)}</div>
                <div class="event-title">${escapeHtml(event.bride_name)} & ${escapeHtml(event.groom_name)}</div>
                <div class="event-location">${escapeHtml(event.campus_name || 'Unknown')}</div>
            </div>`;
        });
        
        html += '</div></div>';
    }
    
    document.getElementById('calendar-days').innerHTML = html;
}

function showListView() {
    document.getElementById('calendar-grid').style.display = 'none';
    document.getElementById('list-view').style.display = 'block';
}

function setView(view) {
    currentView = view;
    
    // Update button states
    document.querySelectorAll('.view-controls .btn').forEach(btn => {
        btn.className = btn.className.replace('btn-primary', 'btn-outline-primary');
    });
    event.target.className = event.target.className.replace('btn-outline-primary', 'btn-primary');
    
    renderCalendar();
}

function previousMonth() {
    currentDate.setMonth(currentDate.getMonth() - 1);
    renderCalendar();
}

function nextMonth() {
    currentDate.setMonth(currentDate.getMonth() + 1);
    renderCalendar();
}

function updateCurrentMonthDisplay() {
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('currentMonth').textContent = 
        `${monthNames[currentDate.getMonth()]} ${currentDate.getFullYear()}`;
}

function isDateToday(year, month, day) {
    const today = new Date();
    return year === today.getFullYear() && 
           month === today.getMonth() && 
           day === today.getDate();
}

function formatTime(timeStr) {
    const time = new Date(`2000-01-01 ${timeStr}`);
    return time.toLocaleTimeString('en-US', { 
        hour: 'numeric', 
        minute: '2-digit', 
        hour12: true 
    });
}

function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function showEventDetails(eventId) {
    const event = eventsData.find(e => e.id == eventId);
    if (!event) return;
    
    const modalBody = document.getElementById('eventModalBody');
    modalBody.innerHTML = `
        <div class="event-detail-card">
            <div class="event-header">
                <h4>Wedding Ceremony</h4>
                <span class="status-badge status-${event.status}">${event.status.charAt(0).toUpperCase() + event.status.slice(1)}</span>
            </div>
            <div class="event-info">
                <div class="info-row">
                    <strong>Couple:</strong> ${escapeHtml(event.bride_name)} & ${escapeHtml(event.groom_name)}
                </div>
                <div class="info-row">
                    <strong>Date:</strong> ${new Date(event.wedding_date).toLocaleDateString('en-US', { 
                        weekday: 'long', 
                        year: 'numeric', 
                        month: 'long', 
                        day: 'numeric' 
                    })}
                </div>
                <div class="info-row">
                    <strong>Time:</strong> ${formatTime(event.wedding_time)}
                </div>
                <div class="info-row">
                    <strong>Venue:</strong> ${escapeHtml(event.campus_name || 'Unknown Campus')}
                </div>
            </div>
        </div>
    `;
    
    document.getElementById('viewEventBtn').href = `<?= site_url('admin/booking/') ?>${event.id}`;
    showModal('eventModal');
}

function showModal(modalId) {
    document.getElementById(modalId).style.display = 'flex';
    document.body.style.overflow = 'hidden';
}

function closeModal(modalId) {
    document.getElementById(modalId).style.display = 'none';
    document.body.style.overflow = 'auto';
}

function exportCalendar() {
    // Simple calendar export functionality
    const events = eventsData.map(event => ({
        title: `Wedding: ${event.bride_name} & ${event.groom_name}`,
        date: event.wedding_date,
        time: event.wedding_time,
        location: event.campus_name || 'Unknown Campus',
        status: event.status
    }));
    
    let csvContent = 'Title,Date,Time,Location,Status\n';
    events.forEach(event => {
        csvContent += `"${event.title}","${event.date}","${event.time}","${event.location}","${event.status}"\n`;
    });
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', 'wedding_calendar_' + new Date().toISOString().slice(0,10) + '.csv');
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

// Close modal on escape key
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const modals = document.querySelectorAll('.modal-overlay');
        modals.forEach(modal => {
            if (modal.style.display === 'flex') {
                closeModal(modal.id);
            }
        });
    }
});
</script>
<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<style>
/* Calendar Navigation */
.calendar-nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 1rem;
}

.calendar-controls {
    display: flex;
    align-items: center;
    gap: 1rem;
}

.calendar-month-title {
    margin: 0;
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--text-primary);
    min-width: 180px;
    text-align: center;
}

.view-controls {
    display: flex;
    gap: 0.5rem;
}

/* Calendar Grid */
.calendar-grid {
    display: flex;
    flex-direction: column;
}

.calendar-header {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    background: var(--accent);
    color: white;
}

.day-header {
    padding: 0.75rem 0.5rem;
    text-align: center;
    font-weight: 600;
    font-size: 0.875rem;
    border-right: 1px solid rgba(255, 255, 255, 0.1);
}

.day-header:last-child {
    border-right: none;
}

.calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
}

.calendar-day {
    min-height: 120px;
    border-right: 1px solid var(--border);
    border-bottom: 1px solid var(--border);
    padding: 0.5rem;
    background: var(--bg-secondary);
    position: relative;
}

.calendar-day:last-child {
    border-right: none;
}

.calendar-day.empty {
    background: var(--bg-tertiary);
}

.calendar-day.today {
    background: var(--warning-light);
}

.day-number {
    font-weight: 600;
    font-size: 0.875rem;
    color: var(--text-primary);
    margin-bottom: 0.25rem;
}

.day-events {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
}

.event-item {
    padding: 0.25rem 0.375rem;
    border-radius: 4px;
    font-size: 0.6875rem;
    cursor: pointer;
    transition: all 0.2s ease;
    border-left: 3px solid;
}

.event-item:hover {
    transform: scale(1.02);
    box-shadow: var(--shadow-md);
}

.event-item.status-pending {
    background: #fff3cd;
    border-left-color: #ffc107;
    color: #856404;
}

.event-item.status-approved {
    background: #d4edda;
    border-left-color: #28a745;
    color: #155724;
}

.event-item.status-completed {
    background: #d1ecf1;
    border-left-color: #17a2b8;
    color: #0c5460;
}

.event-item.status-cancelled {
    background: #f8d7da;
    border-left-color: #dc3545;
    color: #721c24;
}

.event-time {
    font-weight: 600;
    margin-bottom: 0.0625rem;
}

.event-title {
    font-weight: 500;
    margin-bottom: 0.0625rem;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.event-location {
    font-size: 0.625rem;
    opacity: 0.8;
}

/* List View */
.list-view {
    padding: 1.5rem;
}

.events-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.event-list-item {
    display: flex;
    align-items: center;
    gap: 1.25rem;
    padding: 1.25rem;
    background: var(--bg-tertiary);
    border-radius: 8px;
    border: 1px solid var(--border);
}

.event-date-info {
    text-align: center;
    background: var(--accent);
    color: white;
    border-radius: 8px;
    padding: 0.75rem;
    min-width: 70px;
}

.event-day {
    font-size: 1.5rem;
    font-weight: 700;
    line-height: 1;
}

.event-month {
    font-size: 0.75rem;
    margin-top: 0.125rem;
    opacity: 0.9;
}

.event-year {
    font-size: 0.625rem;
    opacity: 0.7;
}

.event-details {
    flex: 1;
}

.event-details h4 {
    margin: 0 0 0.5rem 0;
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--text-primary);
}

.couple-names {
    margin: 0 0 0.5rem 0;
    font-size: 1rem;
    font-weight: 500;
    color: var(--text-secondary);
}

.event-location, .event-time {
    margin: 0 0 0.25rem 0;
    font-size: 0.875rem;
    color: var(--text-tertiary);
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

.event-actions {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 0.5rem;
}

/* Calendar Legend */
.legend-items {
    display: flex;
    gap: 1.25rem;
    flex-wrap: wrap;
}

.legend-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    color: var(--text-secondary);
}

.legend-color {
    width: 16px;
    height: 16px;
    border-radius: 3px;
    border-left: 3px solid;
}

.legend-color.status-pending {
    background: #fff3cd;
    border-left-color: #ffc107;
}

.legend-color.status-approved {
    background: #d4edda;
    border-left-color: #28a745;
}

.legend-color.status-completed {
    background: #d1ecf1;
    border-left-color: #17a2b8;
}

.legend-color.status-cancelled {
    background: #f8d7da;
    border-left-color: #dc3545;
}

/* Empty Calendar State */
.empty-calendar {
    text-align: center;
    padding: 3.75rem 1.25rem;
}

.empty-calendar i {
    font-size: 4rem;
    color: var(--text-muted);
    margin-bottom: 1rem;
}

.empty-calendar h4 {
    margin: 0 0 0.5rem 0;
    font-size: 1.25rem;
    color: var(--text-secondary);
}

.empty-calendar p {
    margin: 0;
    color: var(--text-tertiary);
}

/* Event Detail Modal */
.event-detail-card {
    padding: 0;
}

.event-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid var(--border);
}

.event-header h4 {
    margin: 0;
    font-size: 1.125rem;
    color: var(--text-primary);
}

.event-info {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
}

.info-row {
    font-size: 0.875rem;
    color: var(--text-secondary);
}

.info-row strong {
    color: var(--text-primary);
    margin-right: 0.5rem;
}

/* Status Badges */
.status-badge {
    padding: 0.25rem 0.75rem;
    border-radius: 20px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.status-pending {
    background: #fff3cd;
    color: #856404;
    border: 1px solid #ffeaa7;
}

.status-approved {
    background: #d4edda;
    color: #155724;
    border: 1px solid #c3e6cb;
}

.status-completed {
    background: #d1ecf1;
    color: #0c5460;
    border: 1px solid #bee5eb;
}

.status-cancelled {
    background: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
}

/* Responsive Design */
@media (max-width: 768px) {
    .calendar-nav {
        flex-direction: column;
        gap: 1rem;
    }
    
    .calendar-month-title {
        min-width: auto;
    }
    
    .calendar-day {
        min-height: 80px;
        padding: 0.25rem;
    }
    
    .day-number {
        font-size: 0.75rem;
    }
    
    .event-item {
        font-size: 0.625rem;
        padding: 0.125rem 0.25rem;
    }
    
    .event-list-item {
        flex-direction: column;
        text-align: center;
        gap: 0.75rem;
    }
    
    .event-actions {
        align-items: center;
    }
    
    .legend-items {
        justify-content: center;
    }
}

@media (max-width: 480px) {
    .calendar-days {
        grid-template-columns: repeat(7, 1fr);
    }
    
    .calendar-day {
        min-height: 60px;
        padding: 0.125rem;
    }
    
    .event-item .event-title,
    .event-item .event-location {
        display: none;
    }
}
</style>
<?= $this->endSection() ?>
