<!-- Step 1: Venue & Date Selection (Currently Active) -->
<div class="form-section" data-step="1">
    <?php 
    // Debug: Show what's in the application array for step 1
    if (!empty($application)) {
        echo "<!-- Step 1 Debug - Application data keys: " . implode(', ', array_keys($application)) . " -->";
        echo "<!-- Step 1 selectedCampus: " . ($application['selectedCampus'] ?? 'NOT FOUND') . " -->";
    } else {
        echo "<!-- Step 1 Debug - Application array is empty -->";
    }
    ?>
    <div class="form-section-header">
        <h2>Venue & Date Selection</h2>
        <p>Choose your preferred campus and wedding date</p>
    </div>
    
    <!-- Campus Selection -->
    <div class="campus-selection">
        <h3 class="section-title">
            <i class="fas fa-church"></i>
            Select Campus
        </h3>
        
        <div class="campus-grid">
            
            <?php foreach ($campuses as $campus): ?>
            <div class="campus-card" data-campus="<?= $campus['id'] ?>" onclick="selectCampus('<?= $campus['id'] ?>')">
                <div class="campus-image">
                    <img src="<?= base_url('public/images/campuses/' . $campus['image_path']) ?>" alt="<?= $campus['name'] ?>">
                </div>
                <div class="campus-info">
                    <h4><?= $campus['name'] ?></h4>
                    <p><i class="fas fa-map-marker-alt"></i> <?= $campus['location'] ?></p>
                    <p><i class="fas fa-users"></i> Capacity: <?= $campus['capacity'] ?></p>
                    <p><i class="fas fa-clock"></i> Available: 9:00 AM, 11:00 AM, 1:00 PM (Saturdays only)</p>
                </div>
                <div class="campus-select-indicator">
                    <i class="fas fa-check-circle"></i>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        
        <input type="hidden" id="selectedCampus" name="selectedCampus" value="<?= old('selectedCampus', $application['selectedCampus'] ?? '') ?>" required>
        <?php 
        // Debug: Show what values are being set
        echo "<!-- Debug - Campus value: '" . ($application['selectedCampus'] ?? 'NOT SET') . "' -->";
        echo "<!-- Debug - Date value: '" . ($application['selectedDate'] ?? 'NOT SET') . "' -->";
        echo "<!-- Debug - Time value: '" . ($application['selectedTime'] ?? 'NOT SET') . "' -->";
        ?>
    </div>
    
    <!-- Date & Time Selection -->
    <div class="datetime-selection" id="datetimeSection" style="display: none;">
        <h3 class="section-title">
            <i class="fas fa-calendar-alt"></i>
            Select Date & Time
        </h3>
        
        <div class="calendar-container">
            <div class="calendar-header">
                <button type="button" class="nav-btn" id="prevMonth" onclick="changeMonth(-1)">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <h4 id="currentMonth">December 2025</h4>
                <button type="button" class="nav-btn" id="nextMonth" onclick="changeMonth(1)">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            
            <div class="calendar-grid" id="calendarGrid">
                <div class="day-header">Sun</div>
                <div class="day-header">Mon</div>
                <div class="day-header">Tue</div>
                <div class="day-header">Wed</div>
                <div class="day-header">Thu</div>
                <div class="day-header">Fri</div>
                <div class="day-header">Sat</div>
                
                <!-- Calendar days will be generated by JavaScript -->
            </div>
        </div>
        
        <div class="time-selection" id="timeSelection" style="display: none;">
            <h4>Select Time Slot</h4>
            <p class="time-help-text">
                <i class="fas fa-info-circle"></i>
                Time slots marked as "Booked" or "Pending" are not available for selection.
            </p>
            <div class="time-slots">
                <div class="time-slot" data-time="09:00" onclick="selectTime('09:00')">
                    <i class="fas fa-clock"></i>
                    <span>9:00 AM - 12:00 PM</span>
                    <span class="availability available">Available</span>
                </div>
                <div class="time-slot" data-time="11:00" onclick="selectTime('11:00')">
                    <i class="fas fa-clock"></i>
                    <span>11:00 AM - 2:00 PM</span>
                    <span class="availability available">Available</span>
                </div>
                <div class="time-slot" data-time="13:00" onclick="selectTime('13:00')">
                    <i class="fas fa-clock"></i>
                    <span>1:00 PM - 4:00 PM</span>
                    <span class="availability available">Available</span>
                </div>
            </div>
        </div>
        
        <input type="hidden" id="selectedDate" name="selectedDate" value="<?= old('selectedDate', $application['selectedDate'] ?? '') ?>" required>
        <input type="hidden" id="selectedTime" name="selectedTime" value="<?= old('selectedTime', $application['selectedTime'] ?? '') ?>" required>
        
        <?php 
        // Additional debugging for date
        echo "<!-- Date Input Debug: value='" . old('selectedDate', $application['selectedDate'] ?? '') . "' -->";
        echo "<!-- Time Input Debug: value='" . old('selectedTime', $application['selectedTime'] ?? '') . "' -->";
        echo "<!-- Application array debug: " . (isset($application) ? 'SET' : 'NOT SET') . " -->";
        if (isset($application)) {
            echo "<!-- Application selectedDate key exists: " . (array_key_exists('selectedDate', $application) ? 'YES' : 'NO') . " -->";
        }
        ?>
    </div>
    
    <!-- Selection Summary -->
    <div class="selection-summary" id="selectionSummary" style="display: none;">
        <h3 class="section-title">
            <i class="fas fa-check-circle"></i>
            Your Selection
        </h3>
        
        <div class="summary-card">
            <div class="summary-item">
                <strong>Campus:</strong>
                <span id="summaryCampus">-</span>
            </div>
            <div class="summary-item">
                <strong>Date:</strong>
                <span id="summaryDate">-</span>
            </div>
            <div class="summary-item">
                <strong>Time:</strong>
                <span id="summaryTime">-</span>
            </div>
        </div>
    </div>
</div>

<style>
/* Campus Selection Styles */
.campus-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
}

.campus-card {
    border: 2px solid var(--light-gray);
    border-radius: 12px;
    overflow: hidden;
    cursor: pointer;
    transition: all 0.3s ease;
    position: relative;
    background: var(--white);
}

.campus-card:hover {
    border-color: var(--primary-color);
    transform: translateY(-5px);
    box-shadow: 0 10px 30px rgba(100, 1, 127, 0.1);
}

.campus-card.selected {
    border-color: var(--primary-color);
    background: rgba(100, 1, 127, 0.05);
}

.campus-card.selected .campus-select-indicator {
    opacity: 1;
    transform: scale(1);
}

.campus-image {
    height: 180px;
    overflow: hidden;
}

.campus-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 0.3s ease;
}

.campus-card:hover .campus-image img {
    transform: scale(1.05);
}

.campus-info {
    padding: 20px;
}

.campus-info h4 {
    margin: 0 0 10px 0;
    color: var(--primary-color);
    font-size: 1.2rem;
}

.campus-info p {
    margin: 5px 0;
    color: var(--gray);
    font-size: 0.9rem;
    display: flex;
    align-items: center;
    gap: 8px;
}

.campus-select-indicator {
    position: absolute;
    top: 15px;
    right: 15px;
    width: 30px;
    height: 30px;
    background: var(--primary-color);
    color: var(--white);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transform: scale(0.8);
    transition: all 0.3s ease;
}

/* Calendar Styles */
.calendar-container {
    max-width: 400px;
    margin: 0 auto 30px;
    background: var(--white);
    border: 2px solid var(--light-gray);
    border-radius: 12px;
    overflow: hidden;
}

.calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
    background: var(--primary-color);
    color: var(--white);
}

.calendar-header h4 {
    margin: 0;
    font-size: 1.1rem;
}

.nav-btn {
    background: none;
    border: none;
    color: var(--white);
    cursor: pointer;
    padding: 8px;
    border-radius: 4px;
    transition: background 0.3s ease;
}

.nav-btn:hover {
    background: rgba(255, 255, 255, 0.1);
}

.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: var(--light-gray);
}

.day-header {
    padding: 15px 10px;
    text-align: center;
    font-weight: 600;
    color: var(--gray);
    background: #f8f9fa;
    font-size: 0.9rem;
}

.calendar-day {
    padding: 15px 10px;
    text-align: center;
    background: var(--white);
    cursor: pointer;
    transition: all 0.3s ease;
    border: 2px solid transparent;
    position: relative;
}

.calendar-day:hover {
    background: rgba(100, 1, 127, 0.1);
}

.calendar-day.available {
    color: var(--text-color);
}

.calendar-day.unavailable {
    color: var(--gray);
    background: #f8f9fa;
    cursor: not-allowed;
    position: relative;
}

.calendar-day.unavailable.blocked {
    background: #ffe6e6;
    color: #d32f2f;
    border: 1px solid #ffcdd2;
}

.calendar-day.unavailable.blocked::after {
    content: '🚫';
    position: absolute;
    top: 2px;
    right: 2px;
    font-size: 8px;
    opacity: 0.7;
}

.calendar-day.selected {
    background: var(--primary-color);
    color: var(--white);
    border-color: var(--primary-color);
}

.calendar-day.other-month {
    color: var(--light-gray);
    background: #f8f9fa;
}

/* Time Selection Styles */
.time-help-text {
    background: rgba(52, 152, 219, 0.1);
    color: #2980b9;
    padding: 12px 16px;
    border-radius: 8px;
    font-size: 14px;
    margin-bottom: 20px;
    border-left: 3px solid #3498db;
    display: flex;
    align-items: center;
    gap: 8px;
}

.time-help-text i {
    color: #3498db;
}

.time-slots {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 15px;
    margin-top: 20px;
}

.time-slot {
    padding: 20px;
    border: 2px solid var(--light-gray);
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s ease;
    display: flex;
    align-items: center;
    gap: 15px;
    background: var(--white);
}

.time-slot:hover {
    border-color: var(--primary-color);
    background: rgba(100, 1, 127, 0.05);
}

.time-slot.selected {
    border-color: var(--primary-color);
    background: rgba(100, 1, 127, 0.1);
}

.time-slot i {
    color: var(--primary-color);
    font-size: 1.2rem;
}

.time-slot span {
    flex: 1;
}

.availability {
    font-size: 0.8rem;
    padding: 4px 8px;
    border-radius: 4px;
    font-weight: 600;
}

.availability.available {
    background: rgba(46, 204, 113, 0.1);
    color: var(--success-color);
}

.availability.unavailable {
    background: rgba(231, 76, 60, 0.1);
    color: var(--error-color);
}

.availability.checking {
    background: rgba(255, 193, 7, 0.1);
    color: #856404;
}

/* Time slot unavailable state */
.time-slot.unavailable {
    opacity: 0.5 !important;
    cursor: not-allowed !important;
    background: #f8f9fa !important;
    border-color: #e9ecef !important;
}

.time-slot.unavailable:hover {
    border-color: #e9ecef !important;
    background: #f8f9fa !important;
    transform: none !important;
}

.time-slot.unavailable i {
    color: #6c757d !important;
}

.time-slot.unavailable span {
    color: #6c757d !important;
}

/* Selection Summary Styles */
.summary-card {
    background: rgba(100, 1, 127, 0.05);
    border: 2px solid var(--primary-color);
    border-radius: 12px;
    padding: 25px;
}

.summary-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
    padding: 10px 0;
    border-bottom: 1px solid var(--light-gray);
}

.summary-item:last-child {
    border-bottom: none;
    margin-bottom: 0;
}

.summary-item strong {
    color: var(--primary-color);
}
</style>

<script>
// Global variables
// Initialize currentDate to minimum booking date (6 months from today)
const today = new Date();
const minBookingDate = new Date(today);
minBookingDate.setDate(minBookingDate.getDate() + 180); // 6 months = 180 days

// Start calendar at minimum booking date month
let currentDate = new Date(minBookingDate.getFullYear(), minBookingDate.getMonth(), 1);
let selectedCampusId = null;
let selectedDate = null;
let selectedTime = null;
let campusData = <?= json_encode($campuses) ?>;
let minBookingDateStr = '<?= isset($minBookingDate) ? $minBookingDate : date('Y-m-d', strtotime('+180 days')) ?>';

// Helper function to format date for API without timezone issues
function formatDateForAPI(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

// Check if a specific date is blocked for the selected campus
async function isDateBlocked(campusId, date) {
    if (!campusId) return false;
    
    try {
        const formattedDate = formatDateForAPI(date);
        const response = await fetch(`<?= site_url('api/campuses/') ?>${campusId}/availability/${formattedDate}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest'
            }
        });
        
        const data = await response.json();
        return data.status === 'error'; // If status is error, date is blocked
    } catch (error) {
        console.error('Error checking if date is blocked:', error);
        return false; // Assume not blocked if we can't check
    }
}

// Campus selection function
function selectCampus(campusId) {
    // Remove previous selection
    document.querySelectorAll('.campus-card').forEach(card => {
        card.classList.remove('selected');
    });
    
    // Add selection to clicked campus
    const selectedCard = document.querySelector(`[data-campus="${campusId}"]`);
    if (selectedCard) {
        selectedCard.classList.add('selected');
        selectedCampusId = campusId;
        
        // Update hidden input
        document.getElementById('selectedCampus').value = campusId;
        
        // Show date/time selection section
        document.getElementById('datetimeSection').style.display = 'block';
        
        // Update summary
        const campus = campusData.find(c => c.id == campusId);
        if (campus) {
            document.getElementById('summaryCampus').textContent = campus.name;
        }
        
        // Generate calendar for current month (only if not already generated)
        if (!document.querySelector('.calendar-day')) {
            generateCalendar();
        } else {
            // Regenerate calendar to check blocked dates for the new campus
            generateCalendar();
        }
        
        // Show a brief loading message while checking blocked dates
        if (selectedCampusId) {
            const loadingText = document.createElement('p');
            loadingText.id = 'blockingCheckMessage';
            loadingText.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Checking blocked dates...';
            loadingText.style.textAlign = 'center';
            loadingText.style.color = '#666';
            loadingText.style.fontSize = '0.9rem';
            loadingText.style.marginTop = '10px';
            
            const calendarContainer = document.querySelector('.calendar-container');
            calendarContainer.appendChild(loadingText);
            
            // Remove the message after a short delay
            setTimeout(() => {
                const message = document.getElementById('blockingCheckMessage');
                if (message) {
                    message.remove();
                }
            }, 2000);
        }
        
        // If a date is already selected, check time slot availability for the new campus
        if (selectedDate) {
            const formattedDate = formatDateForAPI(selectedDate);
            checkTimeSlotAvailability(campusId, formattedDate);
        }
        
        // Check completion status and auto-save
        handleSelectionChange();
        
        // Only scroll if this is a user interaction (not during data loading)
        if (event && event.type) {
            document.getElementById('datetimeSection').scrollIntoView({ 
                behavior: 'smooth',
                block: 'start'
            });
        }
    }
}

// Calendar navigation functions
function changeMonth(direction) {
    currentDate.setMonth(currentDate.getMonth() + direction);
    generateCalendar();
}

function generateCalendar() {
    const calendar = document.getElementById('calendarGrid');
    const monthDisplay = document.getElementById('currentMonth');
    
    // Clear existing calendar days (keep headers)
    const existingDays = calendar.querySelectorAll('.calendar-day');
    existingDays.forEach(day => day.remove());
    
    // Update month display
    const months = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'
    ];
    monthDisplay.textContent = `${months[currentDate.getMonth()]} ${currentDate.getFullYear()}`;
    
    // Get first day of month and number of days
    const firstDay = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
    const lastDay = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - firstDay.getDay()); // Start from Sunday
    
    // Generate calendar days (6 weeks = 42 days)
    for (let i = 0; i < 42; i++) {
        const dayDate = new Date(startDate);
        dayDate.setDate(startDate.getDate() + i);
        
        const dayElement = document.createElement('div');
        dayElement.className = 'calendar-day';
        dayElement.textContent = dayDate.getDate();
        
        // Check if day is in current month
        if (dayDate.getMonth() !== currentDate.getMonth()) {
            dayElement.classList.add('other-month');
        } else {
            // Check if date is available (6 months in advance, Saturday only)
            const today = new Date();
            today.setHours(0, 0, 0, 0);
            
            // Calculate minimum booking date (6 months = 180 days from today)
            const minBookingDate = new Date(today);
            minBookingDate.setDate(minBookingDate.getDate() + 180);
            
            // Check if date is Saturday (day 6)
            const isSaturday = dayDate.getDay() === 6;
            
            // Check if date meets requirements: Saturday, at least 6 months away
            if (isSaturday && dayDate >= minBookingDate) {
                dayElement.classList.add('available');
                dayElement.onclick = () => selectDate(dayDate);
                
                // Check if date is blocked for the selected campus (async)
                if (selectedCampusId) {
                    checkAndMarkBlockedDate(dayElement, dayDate, selectedCampusId);
                }
            } else {
                dayElement.classList.add('unavailable');
                if (!isSaturday) {
                    dayElement.title = 'Weddings can only be booked on Saturdays';
                } else if (dayDate < minBookingDate) {
                    const daysShort = Math.ceil((minBookingDate - dayDate) / (1000 * 60 * 60 * 24));
                    dayElement.title = `Wedding date must be at least 6 months (180 days) in advance. This date is ${daysShort} days too early.`;
                } else if (dayDate < today) {
                    dayElement.title = 'Past dates are not available';
                }
            }
        }
        
        calendar.appendChild(dayElement);
    }
}

// Helper function to check and mark blocked dates
async function checkAndMarkBlockedDate(dayElement, dayDate, campusId) {
    try {
        const isBlocked = await isDateBlocked(campusId, dayDate);
        if (isBlocked) {
            dayElement.classList.remove('available');
            dayElement.classList.add('unavailable', 'blocked');
            dayElement.onclick = null;
            dayElement.title = 'This date is blocked for this campus';
            dayElement.style.cursor = 'not-allowed';
        }
    } catch (error) {
        console.error('Error checking blocked date:', error);
        // Keep as available if we can't check
    }
}

// Date selection function
function selectDate(date) {
    console.log('selectDate called with:', date);
    console.log('Selected date object:', date.toString());
    console.log('Selected date local components:', {
        year: date.getFullYear(),
        month: date.getMonth() + 1,
        day: date.getDate()
    });
    
    // Remove previous selection
    document.querySelectorAll('.calendar-day').forEach(day => {
        day.classList.remove('selected');
    });
    
    // Add selection to clicked date
    event.target.classList.add('selected');
    
    selectedDate = date;
    // Fix timezone issue: format date properly without timezone conversion
    const formattedDate = formatDateForAPI(date);
    console.log('Formatted date for API:', formattedDate);
    document.getElementById('selectedDate').value = formattedDate;
    
    // Show time selection
    document.getElementById('timeSelection').style.display = 'block';
    
    // Update summary
    const options = { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    };
    document.getElementById('summaryDate').textContent = date.toLocaleDateString('en-US', options);
    
    // Reset time selection
    selectedTime = null;
    document.getElementById('selectedTime').value = '';
    document.getElementById('summaryTime').textContent = '-';
    document.querySelectorAll('.time-slot').forEach(slot => {
        slot.classList.remove('selected');
    });
    
    // Check time slot availability for the selected date
    checkTimeSlotAvailability(selectedCampusId, formattedDate);
    
    // Check completion status and auto-save
    handleSelectionChange();
    
    // Scroll to time selection
    document.getElementById('timeSelection').scrollIntoView({ 
        behavior: 'smooth',
        block: 'start'
    });
}

// Time selection function
function selectTime(time) {
    // Check if the time slot is available (not disabled/unavailable)
    const timeSlot = document.querySelector(`[data-time="${time}"]`);
    if (timeSlot && timeSlot.classList.contains('unavailable')) {
        // Don't allow selection of unavailable slots
        return;
    }
    
    // Remove previous selection
    document.querySelectorAll('.time-slot').forEach(slot => {
        slot.classList.remove('selected');
    });
    
    // Find and select the time slot
    if (timeSlot) {
        timeSlot.classList.add('selected');
    }
    
    selectedTime = time;
    document.getElementById('selectedTime').value = time;
    
    // Update summary
    const timeSlots = {
        '09:00': '9:00 AM - 12:00 PM',
        '11:00': '11:00 AM - 2:00 PM',
        '13:00': '1:00 PM - 4:00 PM'
    };
    document.getElementById('summaryTime').textContent = timeSlots[time] || time;
    
    // Show selection summary
    document.getElementById('selectionSummary').style.display = 'block';
    
    // Check completion status, auto-save, and enable next button
    handleSelectionChange();
    
    // Only scroll if this is a user interaction (not during data loading)
    if (event && event.type) {
        document.getElementById('selectionSummary').scrollIntoView({ 
            behavior: 'smooth',
            block: 'start'
        });
    }
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', function() {
    console.log('Step 1 initializing...');
    
    // Set current month to minimum booking date month (6 months from today)
    const today = new Date();
    const minDate = new Date(today);
    minDate.setDate(minDate.getDate() + 180); // 6 months = 180 days
    currentDate = new Date(minDate.getFullYear(), minDate.getMonth(), 1);
    
    // Get saved values - check both camelCase and snake_case versions
    const existingCampus = document.getElementById('selectedCampus').value;
    const existingDate = document.getElementById('selectedDate').value;
    const existingTime = document.getElementById('selectedTime').value;
    
    console.log('Raw input values:', {
        campusInput: document.getElementById('selectedCampus'),
        dateInput: document.getElementById('selectedDate'),
        timeInput: document.getElementById('selectedTime')
    });
    
    console.log('Actual HTML input values:', {
        campusValue: document.getElementById('selectedCampus').value,
        campusAttr: document.getElementById('selectedCampus').getAttribute('value'),
        dateValue: document.getElementById('selectedDate').value,
        dateAttr: document.getElementById('selectedDate').getAttribute('value'),
        timeValue: document.getElementById('selectedTime').value,
        timeAttr: document.getElementById('selectedTime').getAttribute('value')
    });
    
    console.log('Saved step 1 data:', {
        campus: existingCampus,
        date: existingDate,
        time: existingTime
    });
    
    // Check if we have all data and should auto-advance to step 2
    const allDataPresent = existingCampus && existingDate && existingTime;
    console.log('All step 1 data present:', allDataPresent);
    console.log('Available campuses:', campusData);
    console.log('Looking for campus ID:', existingCampus, 'Type:', typeof existingCampus);
    
    // Pre-select campus if value exists
    if (existingCampus) {
        console.log('Pre-selecting campus:', existingCampus);
        selectedCampusId = existingCampus;
        
        // Visually select the campus card
        const campusCard = document.querySelector(`[data-campus="${existingCampus}"]`);
        console.log('Looking for campus card with selector:', `[data-campus="${existingCampus}"]`);
        console.log('Found campus card:', campusCard);
        if (campusCard) {
            campusCard.classList.add('selected');
            console.log('Campus card selected');
        } else {
            console.log('Campus card not found for ID:', existingCampus);
            console.log('Available campus cards:', document.querySelectorAll('[data-campus]'));
        }
        
        // Update summary
        const campus = campusData.find(c => c.id == existingCampus);
        if (campus) {
            document.getElementById('summaryCampus').textContent = campus.name;
            console.log('Campus summary updated:', campus.name);
        }
        
        // Show datetime section
        document.getElementById('datetimeSection').style.display = 'block';
        
        // Generate calendar
        generateCalendar();
    }
    
    // Pre-select date if value exists
    if (existingDate) {
        console.log('Pre-selecting date:', existingDate);
        const date = new Date(existingDate + 'T12:00:00'); // Add time to avoid timezone issues
        selectedDate = date;
        currentDate = new Date(date.getFullYear(), date.getMonth(), 1);
        
        // Show datetime section if we have a campus
        if (selectedCampusId) {
            document.getElementById('datetimeSection').style.display = 'block';
        }
        
        generateCalendar();
        
        // Find and select the date
        setTimeout(() => {
            const dayElements = document.querySelectorAll('.calendar-day');
            let dateFound = false;
            dayElements.forEach(element => {
                if (element.textContent == date.getDate() && 
                    !element.classList.contains('other-month') &&
                    !element.classList.contains('unavailable')) {
                    element.classList.add('selected');
                    dateFound = true;
                    console.log('Date selected on calendar:', date.getDate());
                    
                    // Show time selection
                    document.getElementById('timeSelection').style.display = 'block';
                    
                    // Update summary
                    const options = { 
                        weekday: 'long', 
                        year: 'numeric', 
                        month: 'long', 
                        day: 'numeric' 
                    };
                    document.getElementById('summaryDate').textContent = date.toLocaleDateString('en-US', options);
                    
                    // Check time slot availability if campus is selected
                    if (selectedCampusId) {
                        const formattedDate = formatDateForAPI(date);
                        checkTimeSlotAvailability(selectedCampusId, formattedDate);
                    }
                }
            });
            if (!dateFound) {
                console.log('Date not found in calendar for:', date.getDate());
            }
        }, 100);
    }
    
    // Pre-select time if value exists
    if (existingTime) {
        console.log('Pre-selecting time:', existingTime);
        selectedTime = existingTime;
        setTimeout(() => {
            const timeSlot = document.querySelector(`[data-time="${existingTime}"]`);
            if (timeSlot) {
                timeSlot.classList.add('selected');
                console.log('Time slot selected:', existingTime);
                
                // Update summary
                const timeSlots = {
                    '09:00': '9:00 AM - 12:00 PM',
                    '11:00': '11:00 AM - 2:00 PM',
                    '13:00': '1:00 PM - 4:00 PM'
                };
                document.getElementById('summaryTime').textContent = timeSlots[existingTime] || existingTime;
                
                // Show selection summary
                document.getElementById('selectionSummary').style.display = 'block';
                console.log('Selection summary displayed');
            } else {
                console.log('Time slot not found for:', existingTime);
            }
        }, 200);
    }
    
    // Check completion status after initialization
    setTimeout(() => {
        handleSelectionChange();
        
        // If all step 1 data is present, auto-advance to step 2
        if (allDataPresent) {
            console.log('All step 1 data present, auto-advancing to step 2...');
            // Small delay to ensure everything is properly initialized
            setTimeout(() => {
                if (validateStep1()) {
                    nextStep();
                } else {
                    console.log('Step 1 validation failed despite having data');
                }
            }, 500);
        }
    }, 300);
});

// Availability checking function (enhanced with time slot checking)
function checkAvailability(campusId, date) {
    // This can be enhanced to make AJAX calls to check real availability
    // For now, return true for all future dates
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return date >= today;
}

// Check time slot availability for a specific campus and date
function checkTimeSlotAvailability(campusId, date) {
    if (!campusId || !date) {
        return;
    }
    
    console.log('Checking time slot availability for campus:', campusId, 'date:', date);
    console.log('Date type:', typeof date, 'Date value:', date);
    
    // Show loading state
    const timeSlots = document.querySelectorAll('.time-slot');
    timeSlots.forEach(slot => {
        const availability = slot.querySelector('.availability');
        if (availability) {
            availability.textContent = 'Checking...';
            availability.className = 'availability checking';
        }
        slot.style.opacity = '0.7';
        slot.onclick = null;
    });
    
    // Make API call to check availability
    fetch(`<?= site_url('api/campuses/') ?>${campusId}/availability/${date}`, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            'X-Requested-With': 'XMLHttpRequest'
        }
    })
    .then(response => response.json())
    .then(data => {
        console.log('Availability response:', data);
        
        if (data.status === 'error') {
            // Handle blocked dates or other errors
            console.error('Date selection error:', data.message);
            
            // Show error message to user
            alert(`Sorry, this date is not available: ${data.message}`);
            
            // Reset the date selection
            selectedDate = null;
            document.getElementById('selectedDate').value = '';
            document.getElementById('summaryDate').textContent = '-';
            
            // Remove date selection visually
            document.querySelectorAll('.calendar-day').forEach(day => {
                day.classList.remove('selected');
            });
            
            // Hide time selection
            document.getElementById('timeSelection').style.display = 'none';
            document.getElementById('selectionSummary').style.display = 'none';
            
            // Reset time selection
            selectedTime = null;
            document.getElementById('selectedTime').value = '';
            document.getElementById('summaryTime').textContent = '-';
            document.querySelectorAll('.time-slot').forEach(slot => {
                slot.classList.remove('selected');
            });
            
            return;
        }
        
        if (data.status === 'success' && data.time_slots) {
            // Update each time slot based on availability
            data.time_slots.forEach(timeSlotData => {
                const timeSlot = document.querySelector(`[data-time="${timeSlotData.time}"]`);
                if (timeSlot) {
                    const availability = timeSlot.querySelector('.availability');
                    
                    if (timeSlotData.available) {
                        // Time slot is available
                        availability.textContent = 'Available';
                        availability.className = 'availability available';
                        timeSlot.style.opacity = '1';
                        timeSlot.onclick = () => selectTime(timeSlotData.time);
                        timeSlot.style.cursor = 'pointer';
                        timeSlot.classList.remove('unavailable');
                    } else {
                        // Time slot is booked
                        const status = timeSlotData.booking_status || 'booked';
                        availability.textContent = status === 'pending' ? 'Pending' : 'Booked';
                        availability.className = 'availability unavailable';
                        timeSlot.style.opacity = '0.5';
                        timeSlot.onclick = null;
                        timeSlot.style.cursor = 'not-allowed';
                        timeSlot.classList.add('unavailable');
                        timeSlot.title = `This time slot is ${status === 'pending' ? 'pending approval' : 'already booked'}`;
                    }
                }
            });
        } else {
            // Error or no data - reset to default state
            console.error('Error checking availability:', data.message || 'Unknown error');
            resetTimeSlotAvailability();
        }
    })
    .catch(error => {
        console.error('Error checking time slot availability:', error);
        resetTimeSlotAvailability();
    });
}

// Reset time slots to default available state
function resetTimeSlotAvailability() {
    const timeSlots = document.querySelectorAll('.time-slot');
    timeSlots.forEach(slot => {
        const availability = slot.querySelector('.availability');
        if (availability) {
            availability.textContent = 'Available';
            availability.className = 'availability available';
        }
        slot.style.opacity = '1';
        slot.style.cursor = 'pointer';
        slot.classList.remove('unavailable');
        
        // Restore click handler
        const time = slot.dataset.time;
        if (time) {
            slot.onclick = () => selectTime(time);
        }
    });
}

// Validation function
function validateStep1() {
    const campus = document.getElementById('selectedCampus').value;
    const date = document.getElementById('selectedDate').value;
    const time = document.getElementById('selectedTime').value;
    
    if (!campus) {
        alert('Please select a campus.');
        return false;
    }
    
    if (!date) {
        alert('Please select a wedding date.');
        return false;
    }
    
    if (!time) {
        alert('Please select a time slot.');
        return false;
    }
    
    return true;
}

// Check if step 1 is complete and enable/disable next button accordingly
function checkStep1Completion() {
    const campus = document.getElementById('selectedCampus').value;
    const date = document.getElementById('selectedDate').value;
    const time = document.getElementById('selectedTime').value;
    const nextButton = document.getElementById('nextButton');
    
    if (nextButton) {
        if (campus && date && time) {
            nextButton.disabled = false;
            nextButton.classList.remove('disabled');
            // Store data globally for the main navigation system
            window.selectedCampusData = campus;
            window.selectedDateData = date;
            window.selectedTimeData = time;
        } else {
            nextButton.disabled = true;
            nextButton.classList.add('disabled');
        }
    }
}

// Make validateStep1 available globally for the main navigation system
window.validateStep1 = validateStep1;

// Make step 1 functions available globally for data loading
window.selectCampus = selectCampus;
window.selectTime = selectTime;

// Global step navigation variables
let currentStep = 1;
const totalSteps = 4;

// Step navigation functions
function nextStep() {
    // Validate current step before proceeding
    let isValid = false;
    let validationMessage = '';
    
    switch(currentStep) {
        case 1:
            isValid = validateStep1();
            if (!isValid) validationMessage = 'Please select a campus, date, and time slot.';
            break;
        case 2:
            isValid = validateStep2();
            if (!isValid) validationMessage = 'Please complete all required personal details for both bride and groom.';
            break;
        case 3:
            isValid = validateStep3();
            if (!isValid) validationMessage = 'Please provide witness information.';
            break;
        case 4:
            // Can't go beyond step 4
            return;
    }
    
    if (!isValid) {
        alert(validationMessage);
        return;
    }
    
    if (currentStep < totalSteps) {
        // Hide current step
        const currentStepElement = document.querySelector('.form-section[data-step="' + currentStep + '"]');
        if (currentStepElement) {
            currentStepElement.style.display = 'none';
        }
        
        // Move to next step
        currentStep++;
        
        // Show next step
        const nextStepElement = document.querySelector('.form-section[data-step="' + currentStep + '"]');
        if (nextStepElement) {
            nextStepElement.style.display = 'block';
        }
        
        // Update step indicators
        updateStepIndicators();
        updateNavigationButtons();
        
        // Auto-save current progress (as draft)
        autoSaveProgress();
        
        // Scroll to top of the new step
        window.scrollTo({ top: 0, behavior: 'smooth' });
        
        // Initialize step if needed
        if (currentStep === 4) {
            // Populate review summary when reaching step 4
            // Use a longer delay to ensure all form fields are accessible
            setTimeout(function() {
                if (window.populateStep4Review) {
                    window.populateStep4Review();
                } else if (window.populateReviewSummary) {
                    window.populateReviewSummary();
                }
                // Dispatch custom event for step 4 shown
                document.dispatchEvent(new Event('step4shown'));
            }, 300);
        }
    }
}

function previousStep() {
    if (currentStep > 1) {
        // Hide current step
        const currentStepElement = document.querySelector('.form-section[data-step="' + currentStep + '"]');
        if (currentStepElement) {
            currentStepElement.style.display = 'none';
        }
        
        // Move to previous step
        currentStep--;
        
        // Show previous step
        const prevStepElement = document.querySelector('.form-section[data-step="' + currentStep + '"]');
        if (prevStepElement) {
            prevStepElement.style.display = 'block';
        }
        
        // Update step indicators
        updateStepIndicators();
        updateNavigationButtons();
        
        // Scroll to top
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
}

// Update step indicators
function updateStepIndicators() {
    for (let i = 1; i <= totalSteps; i++) {
        const stepIndicator = document.querySelector('.step[data-step="' + i + '"]');
        if (stepIndicator) {
            stepIndicator.classList.remove('active', 'completed');
            
            if (i < currentStep) {
                stepIndicator.classList.add('completed');
            } else if (i === currentStep) {
                stepIndicator.classList.add('active');
            }
        }
    }
}

// Update navigation buttons
function updateNavigationButtons() {
    const prevButton = document.getElementById('prevButton');
    const nextButton = document.getElementById('nextButton');
    
    // Previous button
    if (prevButton) {
        if (currentStep > 1) {
            prevButton.style.display = 'block';
        } else {
            prevButton.style.display = 'none';
        }
    }
    
    // Next button
    if (nextButton) {
        if (currentStep < totalSteps) {
            nextButton.innerHTML = 'Next <i class="fas fa-arrow-right"></i>';
            nextButton.disabled = !isCurrentStepValid();
            // Remove any custom onclick handler
            nextButton.onclick = null;
            nextButton.setAttribute('onclick', 'nextStep()');
        } else {
            nextButton.innerHTML = 'Submit Application <i class="fas fa-paper-plane"></i>';
            nextButton.disabled = !validateAllSteps();
            // Set custom onclick for submission
            nextButton.onclick = function() { submitApplication(); };
        }
    }
}

// Check if current step is valid
function isCurrentStepValid() {
    switch(currentStep) {
        case 1:
            return validateStep1();
        case 2:
            return validateStep2();
        case 3:
            return validateStep3();
        case 4:
            return validateAllSteps();
        default:
            return false;
    }
}

// Make navigation functions available globally
window.nextStep = nextStep;
window.previousStep = previousStep;

// Validation functions for other steps
function validateStep2() {
    const requiredFields = [
        'brideName', 'brideAge', 'brideEmail', 'bridePhone',
        'groomName', 'groomAge', 'groomEmail', 'groomPhone'
    ];
    
    // Check if all required fields are filled
    const allFieldsFilled = requiredFields.every(fieldId => {
        const field = document.getElementById(fieldId);
        return field && field.value.trim() !== '';
    });
    
    // Validate ages are at least 18
    let agesValid = true;
    if (window.validateStep2Ages) {
        agesValid = window.validateStep2Ages();
    }
    
    // Check age values directly as well
    const brideAge = document.getElementById('brideAge');
    const groomAge = document.getElementById('groomAge');
    
    if (brideAge && (parseInt(brideAge.value) < 18 || !brideAge.value)) {
        agesValid = false;
    }
    if (groomAge && (parseInt(groomAge.value) < 18 || !groomAge.value)) {
        agesValid = false;
    }
    
    return allFieldsFilled && agesValid;
}

function validateStep3() {
    // Check witness information (both witnesses required)
    const requiredWitnessFields = [
        'witness1Name', 'witness1Phone', 'witness1IdNumber', 'witness1Relationship',
        'witness2Name', 'witness2Phone', 'witness2IdNumber', 'witness2Relationship'
    ];
    
    const witnessFieldsValid = requiredWitnessFields.every(fieldId => {
        const field = document.getElementById(fieldId);
        return field && field.value.trim() !== '';
    });
    
    return witnessFieldsValid;
}

function validateAllSteps() {
    const acceptTerms = document.getElementById('acceptTerms');
    // Ensure age validation is also checked on final submission
    let agesValid = true;
    if (window.validateStep2Ages) {
        agesValid = window.validateStep2Ages();
    }
    
    // Double-check age values
    const brideAge = document.getElementById('brideAge');
    const groomAge = document.getElementById('groomAge');
    if (brideAge && parseInt(brideAge.value) < 18) agesValid = false;
    if (groomAge && parseInt(groomAge.value) < 18) agesValid = false;
    
    return validateStep1() && validateStep2() && validateStep3() && 
           acceptTerms && acceptTerms.checked;
}

// Populate review summary for step 4
function populateReviewSummary() {
    // Campus info
    if (selectedCampusId && campusData) {
        const campus = campusData.find(c => c.id == selectedCampusId);
        if (campus) {
            document.getElementById('reviewCampus').textContent = campus.name;
        }
    }
    
    // Date and time
    if (selectedDate) {
        const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        document.getElementById('reviewDate').textContent = selectedDate.toLocaleDateString('en-US', options);
    }
    
    if (selectedTime) {
        const timeSlots = {
            '11:00': '11:00 AM',
            '13:00': '1:00 PM'
        };
        document.getElementById('reviewTime').textContent = timeSlots[selectedTime] || selectedTime;
    }
    
    // Personal details
    const brideName = document.getElementById('brideName');
    const groomName = document.getElementById('groomName');
    const brideEmail = document.getElementById('brideEmail');
    const bridePhone = document.getElementById('bridePhone');
    
    if (brideName) document.getElementById('reviewBrideName').textContent = brideName.value || '-';
    if (groomName) document.getElementById('reviewGroomName').textContent = groomName.value || '-';
    if (brideEmail) document.getElementById('reviewEmail').textContent = brideEmail.value || '-';
    if (bridePhone) document.getElementById('reviewPhone').textContent = bridePhone.value || '-';
    
    // Witness details
    const witness1Name = document.getElementById('witness1Name');
    const witness2Name = document.getElementById('witness2Name');
    
    if (witness1Name) document.getElementById('reviewWitness1').textContent = witness1Name.value || '-';
    if (witness2Name) document.getElementById('reviewWitness2').textContent = witness2Name.value || '-';
}

// Submit application function
function submitApplication() {
    if (!validateAllSteps()) {
        alert('Please complete all required fields and accept the terms and conditions.');
        return;
    }
    
    // Show loading state
    const submitButton = document.getElementById('nextButton');
    const originalText = submitButton.innerHTML;
    submitButton.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving Application...';
    submitButton.disabled = true;
    
    // Prepare form data
    const form = document.getElementById('applicationForm');
    if (!form) {
        alert('Form not found. Please refresh the page and try again.');
        return;
    }
    
    const formData = new FormData(form);
    
    // Ensure CSRF token is included in FormData
    // CodeIgniter expects the token as a form field, not a header
    const csrfTokenName = '<?= csrf_token() ?>';
    const csrfInput = form.querySelector(`input[name="${csrfTokenName}"]`);
    
    if (csrfInput && csrfInput.value) {
        // Use the current token value from the form
        formData.set(csrfTokenName, csrfInput.value);
        console.log('CSRF token included:', csrfTokenName, '=', csrfInput.value.substring(0, 10) + '...');
    } else {
        // Try to get token from meta tag or cookie
        const csrfMeta = document.querySelector('meta[name="csrf-token"]');
        if (csrfMeta) {
            formData.append(csrfTokenName, csrfMeta.getAttribute('content'));
        } else {
            // Last resort: use the PHP-generated hash (may be stale)
            formData.append(csrfTokenName, '<?= csrf_hash() ?>');
            console.warn('Using fallback CSRF token - may be stale');
        }
    }
    
    // Debug: Log all form data keys (excluding values for security)
    console.log('Form data keys:', Array.from(formData.keys()));
    
    // Submit via AJAX to save to database
    fetch('<?= site_url('/dashboard/save-application') ?>', {
        method: 'POST',
        body: formData,
        headers: {
            'X-Requested-With': 'XMLHttpRequest'
        },
        credentials: 'same-origin'
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Clean up any draft data since application is now submitted
            localStorage.removeItem('applicationDraft');
            
            // Show success message and redirect
            alert('Application submitted successfully! You will be redirected to your dashboard.');
            window.location.href = '/dashboard';
        } else {
            throw new Error(data.message || 'Failed to submit application');
        }
    })
    .catch(error => {
        console.error('Error submitting application:', error);
        alert('Error submitting application: ' + error.message);
        
        // Restore button state
        submitButton.innerHTML = originalText;
        submitButton.disabled = false;
    });
}

// Auto-save progress (only saves drafts, not final database entries)
function autoSaveProgress() {
    try {
        const form = document.getElementById('applicationForm');
        if (!form) return;
        
        // Only auto-save essential draft data to avoid quota issues
        const draftData = {};
        
        // Get all form inputs, selects, and textareas
        const inputs = form.querySelectorAll('input, select, textarea');
        
        inputs.forEach(input => {
            // Skip certain fields that aren't essential for draft
            if (input.type === 'checkbox' && !input.checked) return;
            if (input.type === 'radio' && !input.checked) return;
            if (input.type === 'file') return; // Skip file inputs
            if (input.name === '<?= csrf_token() ?>') return; // Skip CSRF token
            if (!input.name) return; // Skip unnamed fields
            
            let value = input.value;
            
            // Skip empty values to reduce size
            if (!value || value.trim() === '') return;
            
            // For textareas, limit length to prevent huge data
            if (input.tagName === 'TEXTAREA' && value.length > 500) {
                value = value.substring(0, 500) + '...';
            }
            
            // Handle radio buttons and checkboxes
            if (input.type === 'radio' || input.type === 'checkbox') {
                if (input.checked) {
                    draftData[input.name] = value;
                }
            } else {
                draftData[input.name] = value;
            }
        });
        
        // Add current step
        if (typeof currentStep !== 'undefined') {
            draftData.current_step = currentStep;
        }
        
        // Add selected campus, date, and time if available
        if (typeof selectedCampusId !== 'undefined' && selectedCampusId) {
            draftData.selectedCampus = selectedCampusId;
        }
        if (typeof selectedDate !== 'undefined' && selectedDate) {
            draftData.selectedDate = selectedDate.toISOString().split('T')[0];
        }
        if (typeof selectedTime !== 'undefined' && selectedTime) {
            draftData.selectedTime = selectedTime;
        }
        
        // Convert to JSON and check size
        const jsonData = JSON.stringify(draftData);
        const dataSize = new Blob([jsonData]).size; // Size in bytes
        
        // If data is too large (over 4MB), reduce it further
        if (dataSize > 4 * 1024 * 1024) {
            console.warn('Draft data too large, reducing...');
            // Remove large text fields
            const largeFields = ['bride_address', 'groom_address', 'pastor_recommendation'];
            largeFields.forEach(field => {
                if (draftData[field]) {
                    draftData[field] = draftData[field].substring(0, 200) + '...';
                }
            });
        }
        
        // Clear old drafts before saving to free up space
        try {
            const oldDraft = localStorage.getItem('applicationDraft');
            if (oldDraft) {
                localStorage.removeItem('applicationDraft');
            }
        } catch (e) {
            // Ignore errors when clearing
        }
        
        // Save to localStorage as draft
        localStorage.setItem('applicationDraft', JSON.stringify(draftData));
        
        // Optional: Also save to server as draft (not final submission)
        if (window.scheduleAutoSave) {
            window.scheduleAutoSave();
        }
    } catch (error) {
        if (error.name === 'QuotaExceededError' || error.code === 22) {
            console.warn('localStorage quota exceeded, clearing old data and retrying...');
            try {
                // Clear all application-related localStorage items
                const keysToRemove = [];
                for (let i = 0; i < localStorage.length; i++) {
                    const key = localStorage.key(i);
                    if (key && (key.includes('application') || key.includes('draft'))) {
                        keysToRemove.push(key);
                    }
                }
                keysToRemove.forEach(key => localStorage.removeItem(key));
                
                // Try saving again with minimal data
                const minimalDraft = {
                    current_step: typeof currentStep !== 'undefined' ? currentStep : 1,
                    selectedCampus: typeof selectedCampusId !== 'undefined' ? selectedCampusId : null,
                    selectedDate: typeof selectedDate !== 'undefined' ? selectedDate.toISOString().split('T')[0] : null,
                    selectedTime: typeof selectedTime !== 'undefined' ? selectedTime : null
                };
                localStorage.setItem('applicationDraft', JSON.stringify(minimalDraft));
                console.log('Saved minimal draft due to quota limit');
            } catch (retryError) {
                console.error('Failed to save draft even after clearing:', retryError);
                // Rely on server-side auto-save instead
            }
        } else {
            console.error('Error saving draft to localStorage:', error);
        }
    }
}

// Initialize the form when page loads
document.addEventListener('DOMContentLoaded', function() {
    // Initialize step display - hide all steps except step 1
    for (let i = 2; i <= totalSteps; i++) {
        const stepElement = document.querySelector('.form-section[data-step="' + i + '"]');
        if (stepElement) {
            stepElement.style.display = 'none';
        }
    }
    
    // Show step 1
    const step1Element = document.querySelector('.form-section[data-step="1"]');
    if (step1Element) {
        step1Element.style.display = 'block';
    }
    
    // Initialize navigation buttons
    updateNavigationButtons();
    
    // Add event listeners for form field changes
    const form = document.getElementById('applicationForm');
    if (form) {
        form.addEventListener('input', function() {
            updateNavigationButtons();
        });
        
        form.addEventListener('change', function() {
            updateNavigationButtons();
        });
    }
    
    // Generate initial calendar
    generateCalendar();
}, 300);

// Auto-save functionality
function autoSaveStep1() {
    // Use the global auto-save function
    if (window.scheduleAutoSave) {
        window.scheduleAutoSave(1);
    }
}

// Call auto-save when selections change
function handleSelectionChange() {
    checkStep1Completion();
    autoSaveStep1();
}
</script>
